### ISSUE TITLE
During Setting development environment

### ISSUE THREAD

**Issue by dimsssss** [piskelapp/piskel#818]
### Environment details
* operating system: mint linux 18.3 sylvia

During Setting development environment

Running "watch:prod" (watch) task
Waiting...
(node:32489) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.<anonymous> (/home/park/develop/node/piskel/node_modules/opn/index.js:83:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)

(node:32489) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32489) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

![2018-05-21 17-18-16](https://user-images.githubusercontent.com/24388846/40297511-16d482e4-5d1b-11e8-9539-4f92206f61a3.png)

**Comment by juliandescottes** [comment]
@dimsssss which version of node do you use?

**Comment by dimsssss** [comment]
p{margin-top:0;margin-bottom:0}
    


    v8.11.2
--------- 원본 메일 ---------

    
        보낸사람: Julian Descottes <notifications@github.com>
        받는사람: piskelapp/piskel <piskel@noreply.github.com>
        
            참조: dimsssss <caruen@hanmail.net>, Mention <mention@noreply.github.com>
        
        날짜: 18.06.09 20:12 GMT +0900
        제목: Re: [piskelapp/piskel] During Setting development environment (#818)
        
        
    
    
        @dimsssss which version of node do you use?

**Comment by dimsssss** [comment]
I'm sorry. I am currently using Ubuntu, and the version of the node we are informing is the version of the node we are using in Ubuntu. I will try it on Ubuntu, and if it does not run, I will inform you again.
