### ISSUE TITLE
Opening .piskel file by command line in terminal (LINUX)

### ISSUE THREAD

**Issue by OmkarDev** [piskelapp/piskel#919]
Bug description  

### i dont know if this should be a pull request 

May be Enhancements or Request

i want to open the .piskel file with command line in terminal linux to be specific
it should open by command line if want i mean it is far more easier than going manually opening app
and doing importing
I tried doing ./piskel and then file name but i didn't work giving error

just for error if you want:

```
(function (exports, require, module, __filename, __dirname) { {"modelVersion":2,"piskel":{"name":"Room","description":"","fps":12,"height":64,"width":128,"layers":["{\"name\":\"Layer 1\",\"opacity\":1,\"frameCount\":1,\"chunks\":[{\"layout\":[[0]],\"base64PNG\":\"data:image/png;base64,base64code
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:567:28)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)
    at Module.runMain (module.js:647:10)
    at run (bootstrap_node.js:428:7)
    at startup (bootstrap_node.js:156:9)
    at bootstrap_node.js:543:3
```

what i can assure is it is not because of wrong file or making of wrong file it can manually be open in piskel app by import method

or if there is any error in my doing you can let me know

### Environment details
* operating system: Linux
* offline application version: 0.14.0 64bits #

**Comment by mvuets** [comment]
I'd like to second this report.

I suppose it would have been a feature request to support a command-line file argument, however in my case it's worse, it's a crash:
```
$ piskel title-screen.piskel 
Failed to open startup resource 'natives_blob.bin'.
Failed to open startup resource 'snapshot_blob.bin'.


#
# Fatal error in ../../v8/src/snapshot/natives-external.cc, line 122
# Check failed: holder_.
#

==== C stack trace ===============================

    /home/mvuets/.local/opt/piskel/lib/libnw.so(+0x305699e) [0x7fc8be88799e]
Illegal instruction (core dumped)

```

I too use version 0.14.0 64bit Linux.

Perhaps, it's V8 that gets in the way?..
```
$ piskel --help
No manual entry for piskel
```

**Comment by mvuets** [comment]
**Quick update.** The crash might be caused by my symlink to a **piskel** binary on my computer and running it from somewhere but its own working dir. After cd'ing into a binary's dir, I get the same error as @OmkarDev does.

Also, passing arbitrary options `piskel --help /path/to/file.piskel`reveals NodeJS underneath. So I guess it is indeed a feature request to support opening files from command-line (-:
```
Usage: node [options] [ -e script | script.js ] [arguments] 
       node debug script.js [arguments] 

Options:
  -v, --version         print Node.js version
*snip*
```

Just to give it a **rationale**: I made a [Desktop entry](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html), so Piskel appears in my GNOME applications menu and so I could open a Piskel project by double-clicking it in GNOME Files (Nautilus).

**Comment by Jac08** [comment]
Im a user of Liunx Mint, on 19.x version  i was execute the app  whitout problems, but on the new version (Linxux mint 20 ) i can't, the librety libconf-2.so.4 is now deprecated.

![image](https://user-images.githubusercontent.com/43563147/101460503-4b88bb00-38ff-11eb-9d4a-ed0b25cd1782.png)
